package model;

// Generated 2 nov. 2014 20:01:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Diagnostic generated by hbm2java
 */
@Entity
@Table(name = "diagnostic", catalog = "odontoligie")
public class Diagnostic implements java.io.Serializable {

	private Integer idDiagn;
	private Patient patient;
	private String commentaire;

	public Diagnostic() {
	}

	public Diagnostic(Patient patient) {
		this.patient = patient;
	}

	public Diagnostic(Patient patient, String commentaire) {
		this.patient = patient;
		this.commentaire = commentaire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_diagn", unique = true, nullable = false)
	public Integer getIdDiagn() {
		return this.idDiagn;
	}

	public void setIdDiagn(Integer idDiagn) {
		this.idDiagn = idDiagn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_patient", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "commentaire", length = 65535)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

}
