package model;

// Generated 2 nov. 2014 20:01:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Examradio generated by hbm2java
 */
@Entity
@Table(name = "examradio", catalog = "odontoligie")
public class Examradio implements java.io.Serializable {

	private Integer idExamRadio;
	private Patient patient;
	private String image;
	private String commentaire;
	private String type;
	private String dateExam;

	public Examradio() {
	}

	public Examradio(Patient patient) {
		this.patient = patient;
	}

	public Examradio(Patient patient, String image, String commentaire,
			String type, String dateExam) {
		this.patient = patient;
		this.image = image;
		this.commentaire = commentaire;
		this.type = type;
		this.dateExam = dateExam;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_exam_radio", unique = true, nullable = false)
	public Integer getIdExamRadio() {
		return this.idExamRadio;
	}

	public void setIdExamRadio(Integer idExamRadio) {
		this.idExamRadio = idExamRadio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_patient", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "image", length = 150)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "commentaire", length = 65535)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@Column(name = "type", length = 15)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "date_exam", length = 20)
	public String getDateExam() {
		return this.dateExam;
	}

	public void setDateExam(String dateExam) {
		this.dateExam = dateExam;
	}

}
