package model;

// Generated 2 nov. 2014 20:01:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "odontoligie")
public class Message implements java.io.Serializable {

	private Integer idMessage;
	private int idFrom;
	private int idTo;
	private int idAffich;
	private String textMsg;
	private String objet;

	public Message() {
	}

	public Message(int idFrom, int idTo, int idAffich) {
		this.idFrom = idFrom;
		this.idTo = idTo;
		this.idAffich = idAffich;
	}

	public Message(int idFrom, int idTo, int idAffich, String textMsg,
			String objet) {
		this.idFrom = idFrom;
		this.idTo = idTo;
		this.idAffich = idAffich;
		this.textMsg = textMsg;
		this.objet = objet;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_message", unique = true, nullable = false)
	public Integer getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(Integer idMessage) {
		this.idMessage = idMessage;
	}

	@Column(name = "id_from", nullable = false)
	public int getIdFrom() {
		return this.idFrom;
	}

	public void setIdFrom(int idFrom) {
		this.idFrom = idFrom;
	}

	@Column(name = "id_to", nullable = false)
	public int getIdTo() {
		return this.idTo;
	}

	public void setIdTo(int idTo) {
		this.idTo = idTo;
	}

	@Column(name = "id_affich", nullable = false)
	public int getIdAffich() {
		return this.idAffich;
	}

	public void setIdAffich(int idAffich) {
		this.idAffich = idAffich;
	}

	@Column(name = "text_msg", length = 65535)
	public String getTextMsg() {
		return this.textMsg;
	}

	public void setTextMsg(String textMsg) {
		this.textMsg = textMsg;
	}

	@Column(name = "objet", length = 30)
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

}
