package model;

// Generated 2 nov. 2014 20:01:30 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "patient", catalog = "odontoligie")
public class Patient implements java.io.Serializable {

	private Integer idPatient;
	private Medecin medecin;
	private String numDossier;
	private String dateNaissance;
	private String sexe;
	private String nom;
	private String prenom;
	private String cin;
	private String tele;
	private String adresse;
	private String photoFace;
	private String photoProfil;
	private Set examradios = new HashSet(0);
	private Set examcliniques = new HashSet(0);
	private Set diagnostics = new HashSet(0);
	private Set traitChirs = new HashSet(0);
	private Set collaborations = new HashSet(0);
	private Set traitMedicals = new HashSet(0);
	private Set examanatomopaths = new HashSet(0);
	private Set suivis = new HashSet(0);

	public Patient() {
	}

	public Patient(Medecin medecin, String numDossier) {
		this.medecin = medecin;
		this.numDossier = numDossier;
	}

	public Patient(Medecin medecin, String numDossier, String dateNaissance,
			String sexe, String nom, String prenom, String cin, String tele,
			String adresse, String photoFace, String photoProfil,
			Set examradios, Set examcliniques, Set diagnostics, Set traitChirs,
			Set collaborations, Set traitMedicals, Set examanatomopaths,
			Set suivis) {
		this.medecin = medecin;
		this.numDossier = numDossier;
		this.dateNaissance = dateNaissance;
		this.sexe = sexe;
		this.nom = nom;
		this.prenom = prenom;
		this.cin = cin;
		this.tele = tele;
		this.adresse = adresse;
		this.photoFace = photoFace;
		this.photoProfil = photoProfil;
		this.examradios = examradios;
		this.examcliniques = examcliniques;
		this.diagnostics = diagnostics;
		this.traitChirs = traitChirs;
		this.collaborations = collaborations;
		this.traitMedicals = traitMedicals;
		this.examanatomopaths = examanatomopaths;
		this.suivis = suivis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_patient", unique = true, nullable = false)
	public Integer getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(Integer idPatient) {
		this.idPatient = idPatient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_medecin", nullable = false)
	public Medecin getMedecin() {
		return this.medecin;
	}

	public void setMedecin(Medecin medecin) {
		this.medecin = medecin;
	}

	@Column(name = "num_dossier", nullable = false, length = 20)
	public String getNumDossier() {
		return this.numDossier;
	}

	public void setNumDossier(String numDossier) {
		this.numDossier = numDossier;
	}

	@Column(name = "date_naissance", length = 20)
	public String getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(String dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "sexe", length = 30)
	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	@Column(name = "nom", length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "cin", length = 30)
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Column(name = "tele", length = 30)
	public String getTele() {
		return this.tele;
	}

	public void setTele(String tele) {
		this.tele = tele;
	}

	@Column(name = "adresse", length = 70)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "photo_face", length = 150)
	public String getPhotoFace() {
		return this.photoFace;
	}

	public void setPhotoFace(String photoFace) {
		this.photoFace = photoFace;
	}

	@Column(name = "photo_profil", length = 150)
	public String getPhotoProfil() {
		return this.photoProfil;
	}

	public void setPhotoProfil(String photoProfil) {
		this.photoProfil = photoProfil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set getExamradios() {
		return this.examradios;
	}

	public void setExamradios(Set examradios) {
		this.examradios = examradios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set getExamcliniques() {
		return this.examcliniques;
	}

	public void setExamcliniques(Set examcliniques) {
		this.examcliniques = examcliniques;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set getDiagnostics() {
		return this.diagnostics;
	}

	public void setDiagnostics(Set diagnostics) {
		this.diagnostics = diagnostics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set getTraitChirs() {
		return this.traitChirs;
	}

	public void setTraitChirs(Set traitChirs) {
		this.traitChirs = traitChirs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set getCollaborations() {
		return this.collaborations;
	}

	public void setCollaborations(Set collaborations) {
		this.collaborations = collaborations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set getTraitMedicals() {
		return this.traitMedicals;
	}

	public void setTraitMedicals(Set traitMedicals) {
		this.traitMedicals = traitMedicals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set getExamanatomopaths() {
		return this.examanatomopaths;
	}

	public void setExamanatomopaths(Set examanatomopaths) {
		this.examanatomopaths = examanatomopaths;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set getSuivis() {
		return this.suivis;
	}

	public void setSuivis(Set suivis) {
		this.suivis = suivis;
	}

}
