package model;

// Generated 2 nov. 2014 20:01:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Suivi generated by hbm2java
 */
@Entity
@Table(name = "suivi", catalog = "odontoligie")
public class Suivi implements java.io.Serializable {

	private Integer idSuivi;
	private Patient patient;
	private String image;
	private String commentaire;
	private String dateExam;

	public Suivi() {
	}

	public Suivi(Patient patient) {
		this.patient = patient;
	}

	public Suivi(Patient patient, String image, String commentaire,
			String dateExam) {
		this.patient = patient;
		this.image = image;
		this.commentaire = commentaire;
		this.dateExam = dateExam;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_suivi", unique = true, nullable = false)
	public Integer getIdSuivi() {
		return this.idSuivi;
	}

	public void setIdSuivi(Integer idSuivi) {
		this.idSuivi = idSuivi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_patient", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "image", length = 150)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "commentaire", length = 65535)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@Column(name = "date_exam", length = 20)
	public String getDateExam() {
		return this.dateExam;
	}

	public void setDateExam(String dateExam) {
		this.dateExam = dateExam;
	}

}
