package model;

// Generated 2 nov. 2014 20:01:30 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TraitMedical generated by hbm2java
 */
@Entity
@Table(name = "trait_medical", catalog = "odontoligie")
public class TraitMedical implements java.io.Serializable {

	private Integer idTraitMed;
	private Patient patient;
	private String commentaire;

	public TraitMedical() {
	}

	public TraitMedical(Patient patient) {
		this.patient = patient;
	}

	public TraitMedical(Patient patient, String commentaire) {
		this.patient = patient;
		this.commentaire = commentaire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_trait_med", unique = true, nullable = false)
	public Integer getIdTraitMed() {
		return this.idTraitMed;
	}

	public void setIdTraitMed(Integer idTraitMed) {
		this.idTraitMed = idTraitMed;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_patient", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "commentaire", length = 65535)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

}
